### ISSUE TITLE
input string with spaces in C++

### ISSUE THREAD

**Issue by surajwate** [surajwate/TheCplusplusWorkshop#1]
https://github.com/surajwate/TheCplusplusWorkshop/blob/7f39bbd25bc493683ff66855a3120f229bad084f/Activity03/main.cpp#L19

When I try to input a string with space in the variable "name", the program goes into an infinite loop. I tried getline(), but it is not working. Please suggest the correction in the code.

**Comment by przmktrc** [comment]
Well,
std::cin "tokenizes" the input, separating different "tokens" with whitespaces. If you want to read a string with spaces, you either use std::cin in a loop, or (preferably) you use std::getline(), though I believe you have to call it twice since at first it will read just a newline character from the previous I/O operation.

I'm kinda new to using github, so a quick question: what is that tab "Assignees"? I don't see any button to like sign up for the fix, so is it you assigns me for it? I would love to fix that, as I said, I'm new to using github and I'd like to get some experience.

**Comment by surajwate** [comment]
Thanks, @przmktrc . This solved the issue. I think you found your way around GitHub.
